services:
  api:
    build: .
    command: sh -c "pnpm --filter @repo/database db:generate && pnpm --filter @repo/database db:migrate && pnpm --filter @repo/database db:seed && pnpm --filter api dev"
    env_file:
      - apps/api/.env
    ports:
      - '3001:3001'

  web:
    build: .
    command: pnpm --filter web exec next dev --turbo --hostname 0.0.0.0 --port 3000
    env_file:
      - apps/web/.env
    ports:
      - '3000:3000'
    depends_on:
      - api
